const { Model, DataTypes } = require('sequelize');

const sequelize = require('../config/connection.js');
const { STRING } = require('sequelize');

class Tag extends Model {}

Tag.init(
  {

     // ids are auto generated by sequelize
     tag_name: {
      type: DataTypes.STRING
     }
    // define columns
    /*
    * `Tag`

  * `id`
  
    * Integer.
  
    * Doesn't allow null values.
  
    * Set as primary key.
  
    * Uses auto increment.

  * `tag_name`
  
    * String.


*/
  },
  {
    sequelize,
    timestamps: false,
    freezeTableName: true,
    underscored: true,
    modelName: 'tag',
  }
);

module.exports = Tag;
